sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install --upgrade pip wheel
  - pip install nose2
  - pip install .

script:
  - nose2 -P tests
